name: Activatebrands
favicon: null
layout_spectrum: 0.7360676329117268
typography_spectrum: 0.3862105682492256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.08077102224342525
  lightness: 0.7132562089245766
  saturation: 0.8888227236457169
  rhythmicContrast: 0.24125924124382436
purpose: []
